USE master
Go
ALTER DATABASE ACNUR ADD FILEGROUP [MAIN_DATA_FILEGROUP]
GO

ALTER DATABASE ACNUR ADD FILE 
(
	NAME = N'Main_data', 
	FILENAME = 'C:\DataFile\Main_Data.ndf', 
	SIZE = 512000KB, 
	FILEGROWTH = 819200KB 
) TO FILEGROUP [MAIN_DATA_FILEGROUP]
GO