USE master
Go
ALTER DATABASE ACNUR ADD FILEGROUP [HEAD_DATA_FILEGROUP]
GO

ALTER DATABASE ACNUR ADD FILE 
(
	NAME = N'Head_data', 
	FILENAME = '/var/opt/mssql/data/Head_Data.ndf', 
	SIZE = 512000KB, 
	FILEGROWTH = 819200KB 
) TO FILEGROUP [HEAD_DATA_FILEGROUP]
GO